### ISSUE TITLE
Document how you created these fonts

### ISSUE THREAD

**Issue by amake** [hirofumii/Noto-Sans-CJK-JP.min#1]
I'm curious as to how you created these fonts. Did you convert from the official OTF release? What tools did you use?

**Comment by hiz8** [comment]
Hi amake!

These fonts are generated using freeware.

- [Subset font maker(Japanese)](https://opentype.jp/subsetfontmk.htm)
- [WOFF Converter(Japanese)](https://opentype.jp/woffconv.htm)

Originally I want to generate it with a script, but it does not work...

**Comment by amake** [comment]
Thank you for the information! I have also had trouble converting Noto CJK. It seems that many tools are unable to handle them. I will check out the ones you mentioned.
